version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-sinatra
    docker:      
      - image: circleci/ruby:2.5.5
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            apk --no-cache add curl
            pip install wget
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run: echo "Initializing build with docker stack"
      - run: docker swarm init
      - run: docker stack deploy -c stackfile.yml bitroid
      - run: sleep 90
      - run: docker service ps bitroid_app
      - run: docker service ls
      - run: docker ps -a
  
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      
      - run: bundle install --path vendor/bundle

      - run:          
        name: docker-image
        command: sudo docker build --rm -t gcr.io/sinatra-app/sinatra-app:v3 .

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build