version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-sinatra
    docker:
      - image: circleci/ruby:2.5.5
    steps:
      - checkout

      - run: bundle install --path vendor/bundle

      - setup_remote_docker

      - run:          
          name: docker-image
          command: sudo docker build --rm -t gcr.io/sinatra-app/sinatra-app:v3 .
