version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-sinatra
    docker:      
      - image: circleci/ruby:2.5.5
    steps:
      - checkout
      - setup_remote_docker

      - type: setup-docker-engine
      - type: shell
        name: Verify Docker Works
        command: |
          docker --version
          docker run hello-world
          
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      
      - run: bundle install --path vendor/bundle

      - run:          
        name: docker-image
        command: sudo docker build --rm -t gcr.io/sinatra-app/sinatra-app:v3 .

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build