version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-sinatra
    docker:
      - image: circleci/ruby:2.5.5
        environment:
          TESTOPTS: "--ci-dir=/tmp/test-results"
          APP_ENV: test
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: sinatra-demo-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: sinatra-demo-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results

  docker-image:
    machine: true
    steps:
      - checkout
      - run:
          name: docker-image
          command: docker build --rm -t asia.gcr.io/${PROJECT}/${DOCKER_IMAGE}:${VERSION} .
