version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-sinatra
    docker:      
      - image: circleci/ruby:2.5.5
    steps:
      - checkout

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - type: shell
        name: Install Docker Client
        command: |
          echo "test"
          curl -L -o /tmp/docker.tgz https://get.docker.com/builds/Linux/x86_64/docker-1.12.3.tgz
          tar -xz -C /tmp -f /tmp/docker.tgz
          sudo mv /tmp/docker/docker* /usr/bin/

          sudo curl -L "https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
          sudo chmod +x  /usr/bin/docker-compose

      - type: shell
        name: Verify Docker Works
        command: |
          docker --version
          docker run hello-world

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      
      - run: bundle install --path vendor/bundle

      - run:          
        name: docker-image
        command: sudo docker build --rm -t gcr.io/sinatra-app/sinatra-app:v3 .

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build